name: alta
favicon: null
layout_spectrum: 0.6550851159263402
typography_spectrum: 0.16714256908744574
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5254202128853649
  lightness: 0.11405979236587882
  saturation: 0.6364024772774428
  rhythmicContrast: 0.29300444130785763
purpose: []
